# -*- python -*-
import os

from lsst.sconsUtils import scripts, env, targets

drpStellaDataDir = env.ProductDir("drp_stella_data")

if drpStellaDataDir:
	# copy DRP_STELLA_DATA_DIR to the test's environment
	env["ENV"]["DRP_STELLA_DATA_DIR"] = drpStellaDataDir
	scripts.BasicSConscript.tests()

