# -*- python -*-
from lsst.sconsUtils import scripts
scripts.BasicSConscript.lib(src=Glob("#src/*.cc")+Glob("#src/*.f")+Glob("#src/cmpfit-1.2/*.cc")+Glob("#src/kriging/*.cc")+Glob("#src/utils/*.cc")+Glob("#src/math/*.cc"))
