import os
import lsst.sconsUtils

# scons steals our environment away, so we have to reinstate it
env = lsst.sconsUtils.env.Clone()
for name in ("PYTHONPATH", "LD_LIBRARY_PATH", "DYLD_LIBRARY_PATH", "PATH"):
    if name in os.environ:
        env.AppendENVPath(name, os.environ[name])

# we may need an explicit library load path specified in the command
libpath = lsst.sconsUtils.utils.libraryLoaderEnvironment()

# We always run these commands with an explicit python rather than relying on the shebang
python = f"{libpath} python"

obsPfs = lsst.sconsUtils.env.ProductDir('obs_pfs')

command = f"{python} {obsPfs}/bin/createHeaderFixes.py {obsPfs}/corrections"
env.AlwaysBuild(env.Command("corrections", lsst.sconsUtils.targets["shebang"], command))
